export const projects = [
  {
    id: '1',
    title: 'Modern Brand Identity',
    category: 'branding',
    description: 'Complete brand identity design for a tech startup',
    imageUrl: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Logo', 'Brand Guide', 'Identity'],
    year: '2024',
  },
  {
    id: '2',
    title: 'E-Commerce Website',
    category: 'web',
    description: 'UI/UX design for a premium e-commerce platform',
    imageUrl: 'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['UI/UX', 'Web Design', 'E-commerce'],
    year: '2024',
  },
  {
    id: '3',
    title: 'Magazine Editorial',
    category: 'print',
    description: 'Creative editorial design for fashion magazine',
    imageUrl: 'https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Editorial', 'Print', 'Layout'],
    year: '2023',
  },
  {
    id: '4',
    title: 'Character Illustration',
    category: 'illustration',
    description: 'Custom character design for mobile game',
    imageUrl: 'https://images.pexels.com/photos/1619791/pexels-photo-1619791.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Character', 'Digital Art', 'Game'],
    year: '2024',
  },
  {
    id: '5',
    title: 'Corporate Branding',
    category: 'branding',
    description: 'Brand refresh for established financial company',
    imageUrl: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Corporate', 'Rebrand', 'Strategy'],
    year: '2023',
  },
  {
    id: '6',
    title: 'Mobile App Design',
    category: 'web',
    description: 'Intuitive fitness tracking app interface',
    imageUrl: 'https://images.pexels.com/photos/147413/twitter-facebook-together-exchange-of-information-147413.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Mobile', 'App', 'Fitness'],
    year: '2024',
  },
  {
    id: '7',
    title: 'Packaging Design',
    category: 'print',
    description: 'Luxury packaging for organic skincare line',
    imageUrl: 'https://images.pexels.com/photos/3735186/pexels-photo-3735186.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Packaging', 'Product', 'Luxury'],
    year: '2023',
  },
  {
    id: '8',
    title: 'Abstract Art Series',
    category: 'illustration',
    description: 'Digital illustration collection for art gallery',
    imageUrl: 'https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Abstract', 'Digital', 'Art'],
    year: '2024',
  },
  {
    id: '9',
    title: 'Restaurant Branding',
    category: 'branding',
    description: 'Complete visual identity for farm-to-table restaurant',
    imageUrl: 'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&w=800',
    tags: ['Restaurant', 'Food', 'Identity'],
    year: '2023',
  },
];
